package main.scala

class ImageCategory extends Category {
  object Type extends Enumeration {
    val Z1 = Value("Movie")
    val Z2 = Value("Series")
    val Z3 = Value("Book")
    val Z4 = Value("Erotic")
  }

  object Format extends Enumeration {
    val A1 = Value("DivX")
    val A2 = Value("WMV")
    val A3 = Value("MPG")
    val A4 = Value("DVD5")
    val A5 = Value("HD Overig")
    val A6 = Value("ePub")
    val A7 = Value("Bluray")
    val A10 = Value("x264")
    val A11 = Value("DVD9")
  }

  object Source extends Enumeration {
    val B1 = Value("Cam")
    val B3 = Value("Promo")
    val B4 = Value("Retail")
    val B5 = Value("TV")
    val B8 = Value("R5")
    val B10 = Value("Telesync")
    val B11 = Value("Scan")
  }

  object Language extends Enumeration {
    val C1 = Value("No subtitles")
    val C2 = Value("Dutch subtitles (external)")
    val C3 = Value("Dutch subtitles (ingebakken)")
    val C4 = Value("English subtitles (external)")
    val C5 = Value("English subtitles (ingebakken)")
    val C7 = Value("Dutch subtitles (instelbaar)")
    val C8 = Value("English subtitles (instelbaar)")
    val C11 = Value("English Audio")
    val C12 = Value("Dutch Audio")
    val C13 = Value("German Audio/Written")
    val C14 = Value("French Audio/Written")
    val C15 = Value("Spanish Audio/Written")
    val C16 = Value("Asian Audio/Written")
  }

  object Genre extends Enumeration {
    val D1 = Value("Action")
    val D2 = Value("Adventure")
    val D3 = Value("Animation")
    val D4 = Value("Cabaret")
    val D5 = Value("Comedy")
    val D6 = Value("Crime")
    val D7 = Value("Documentary")
    val D8 = Value("Drama")
    val D9 = Value("Family")
    val D10 = Value("Fantasy")
    val D11 = Value("Arthouse")
    val D12 = Value("Television")
    val D13 = Value("Horror")
    val D14 = Value("Music")
    val D15 = Value("Musical")
    val D16 = Value("Mystery")
    val D17 = Value("Romance")
    val D18 = Value("Science Fiction")
    val D19 = Value("Sports")
    val D20 = Value("Short")
    val D21 = Value("Thriller")
    val D22 = Value("War")
    val D23 = Value("Western")
    val D29 = Value("Asian")
    val D30 = Value("Anime")
    val D31 = Value("Cover")
    val D32 = Value("Comic")
    val D33 = Value("Cartoon")
    val D34 = Value("Kids")
    val D35 = Value("Business")
    val D36 = Value("Computer")
    val D37 = Value("Hobby")
    val D38 = Value("Cooking")
    val D39 = Value("Knutselen")
    val D40 = Value("Handwerk")
    val D41 = Value("Health")
    val D42 = Value("History")
    val D43 = Value("Psychology")
    val D44 = Value("Newspaper")
    val D45 = Value("Magazine")
    val D46 = Value("Science")
    val D47 = Value("Woman")
    val D48 = Value("Religion")
    val D49 = Value("Roman")
    val D50 = Value("Biography")
    val D51 = Value("Detective")
    val D52 = Value("Animals")
    val D54 = Value("Travel")
    val D56 = Value("Non-fiction")
    val D58 = Value("Poetry")
    val D59 = Value("Fairytale")
    val D27 = Value("Bi")
    val D26 = Value("Lesbo")
    val D25 = Value("Homo")
    val D24 = Value("Hetero")
    val D77 = Value("Amateur")
    val D78 = Value("Group")
    val D79 = Value("POV")
    val D80 = Value("Solo")
    val D81 = Value("Young")
    val D82 = Value("Soft")
    val D83 = Value("Fetisj")
    val D84 = Value("Old")
    val D85 = Value("BBW")
    val D86 = Value("SM")
    val D87 = Value("Rough")
    val D88 = Value("Ebony")
    val D89 = Value("Hentai")
    val D90 = Value("Outdoors")
  }
}
